[project]
name = "projet-13"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "fastapi[standard]>=0.141.1",
    "google-api-python-client>=2.200.0",
    "httpx>=0.28.1",
    "langchain>=1.4.2",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.11",
    "openai>=3.15.0",
    "pydantic>=2.13.5",
    "pymilvus>=3.0.2",
    "python-chess>=1.999",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.1.0",
]
